# примеры API-запросов

@base = http://localhost:8000
@baseApiUrl = http://localhost:8000/api

# аутентификация
GET {{base}}/accounts/login/

###
# POST {{base}}/accounts/login/
# Content-Type: multipart/form-data

# {
#   "csrfmiddlewaretoken":"a7TqwTk2UzwEET6RWMA6TxgaEp2xZxM8",
#   "username": "unker",
#   "password": "11111111q"
# }

###


# 
OPTIONS {{base}}/login/

###

# аутентификация
POST {{baseApiUrl}}/login/
Content-Type: application/json

{
  "username": "unker",
  "password": "11111111q"
}

###

# аутентификация
POST {{base}}/logout/
Content-Type: application/json

{
  "username": "unker"
}

###

# создание пользователя
POST {{baseApiUrl}}/register/
Content-Type: application/json

{
  "username": "unker",
  "email": "test@example.com",
  "first_name": "Test",
  "last_name": "User",
  "password1": "testpassword",
  "password2": "testpassword"
}
