services:
  web:
    build: .
    command: >
      bash -c "
      gunicorn --timeout 120 cloud_storage.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
