services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
