networks:
  app-network:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - SERVER_IP=123
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/server.backend.conf:/etc/nginx/conf.d/server.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
    networks:
      - app-network
    volumes:
      - ./users_files:/usr/src/app/users_files
